<a href="https://colab.research.google.com/github/vscamachos/notebookColabs/blob/master/EntregaFinalSistemasInteligentes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import tensorflow as tf # tensorflow 2.0
from keras.datasets import mnist
import keras
import numpy as np
seed=0
np.random.seed(seed) # fix random seed
tf.random.set_seed(seed)
# input image dimensions
num_classes = 10 # 10 digits

img_rows, img_cols = 28, 28 # number of pixels 

# the data, shuffled and split between train and test sets
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

In [15]:
Y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [16]:
X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1) 
X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

# cast floats to single precision
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# rescale data in interval [0,1]
X_train /= 255
X_test /= 255

In [17]:
Y_train = keras.utils.to_categorical(Y_train, num_classes)
Y_test = keras.utils.to_categorical(Y_test, num_classes)

# Building the model

In [19]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten 
from keras.layers import MaxPooling2D, Dropout
model = Sequential()#add model layers
model.add(Conv2D(32, kernel_size=(5, 5),
                     activation='relu',
                     input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
# add second convolutional layer with 20 filters
model.add(Conv2D(64, (5, 5), activation='relu'))
    
# add 2D pooling layer
model.add(MaxPooling2D(pool_size=(2, 2)))
    
# flatten data
model.add(Flatten())
    
# add a dense all-to-all relu layer
model.add(Dense(1024, activation='relu'))
    
# apply dropout with rate 0.5
model.add(Dropout(0.5))
    
# soft-max layer
model.add(Dense(num_classes, activation='softmax'))

# Compiling the model

In [20]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Training the model

In [21]:
#train the model
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=3)

Epoch 1/3
1875/1875 [==============================] - 92s 49ms/step - loss: 0.1197 - accuracy: 0.9640 - val_loss: 0.0280 - val_accuracy: 0.9908
Epoch 2/3
1875/1875 [==============================] - 92s 49ms/step - loss: 0.0431 - accuracy: 0.9875 - val_loss: 0.0304 - val_accuracy: 0.9920
Epoch 3/3
1875/1875 [==============================] - 91s 49ms/step - loss: 0.0310 - accuracy: 0.9902 - val_loss: 0.0348 - val_accuracy: 0.9888


# Evaluate the model

In [22]:
# evaluate the model
score = model.evaluate(X_test, Y_test, verbose=1)

# print performance
print()
print('Test loss:', score[0])
print('Test accuracy:', score[1])

313/313 [==============================] - 4s 12ms/step - loss: 0.0348 - accuracy: 0.9888

Test loss: 0.034810978919267654
Test accuracy: 0.9887999892234802


# Make predictions

In [24]:
#predict first 4 images in the test set
model.predict_classes(X_test[:4])

array([7, 2, 1, 0])

In [25]:
#predict first 4 images in the test set
model.predict(X_test[:4])

array([[4.3508745e-11, 5.5577201e-09, 3.2012558e-08, 2.8436233e-09,
        2.2232287e-09, 5.7946491e-11, 5.7529166e-13, 9.9999964e-01,
        4.0920362e-10, 4.1273356e-07],
       [1.0461855e-07, 1.8336944e-07, 9.9999964e-01, 1.8937839e-10,
        3.4216338e-10, 7.1998092e-14, 2.5836187e-09, 2.0432472e-11,
        1.0092963e-09, 1.1672176e-11],
       [3.0586374e-08, 9.9999642e-01, 4.1803608e-07, 7.4485612e-11,
        9.1727408e-08, 6.7047505e-09, 3.6099824e-08, 2.7537310e-06,
        1.9672680e-07, 1.5063838e-08],
       [9.9999940e-01, 1.2719936e-10, 3.2615515e-07, 1.7418321e-10,
        3.2996592e-10, 7.9837893e-11, 1.1766033e-07, 2.9635623e-09,
        4.7274202e-09, 1.2473525e-07]], dtype=float32)

In [28]:
#actual results for first 4 images in test set
Y_test[:4]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)